### ISSUE TITLE
The `Guides` drop down gets overlapped by the search bar drop down

### ISSUE THREAD

**Issue by Herraj** [mdn/MDN-feedback#14]
I can provide an screenshot for reference 

Steps to reproduce:
1. Search something in the search bar and _do not_ click any of the results. 
2. Hover your mouse over the `Guides` on the top bar
3. The `Guides` drop down's bottom right edge gets overlapped by the search bar drop down

Would be nice if the `Guides` drop down had a higher `z-index` than the search drop down

**Comment by fiji-flo** [comment]
Thank you. The adjustments have been deployed!
