### ISSUE TITLE
Color contrast in HEADER search on HOME page

### ISSUE THREAD

**Issue by estelle** [mdn/MDN-feedback#15]
While the main search seems OK (didn't test), the `mark` hilite on the search drop down in the search in the header bar makes the text illegible even for those without vision issues

**Comment by fiji-flo** [comment]
Did you test it in dark or light mode?

**Comment by fiji-flo** [comment]
Thanks. I changed it to use the _category_ color with good contrast.

**Comment by fiji-flo** [comment]
That's now addressed. Thank you for reporting.
