### ISSUE TITLE
Inconsistent breadcrumbs w/ MDN Plus

### ISSUE THREAD

**Issue by pdehaan** [mdn/MDN-feedback#44]
### Steps to reproduce
1. Go to https://developer.mozilla.org/en-US/plus/docs/features/notifications
2. Observe the _[MDN Plus](https://developer.mozilla.org/en-US/plus) &gt; [Notifications](https://developer.mozilla.org/en-US/plus/docs/features/notifications)_ breadcrumbs near the top of the page.
3. Go to https://developer.mozilla.org/en-US/plus/notifications (so NOT the docs/features page, but the actual feature)
4. No breadcrumbs

### Actual results
No breadcrumbs while using the feature.

### Expected results
🤷  Not sure if we use breadcrumbs everywhere for consistency, or just close this. 

I guess the one major caveat here would be **MDN Plus &raquo; Notifications** might be different from **MDN Plus &raquo; Notifications** depending on which page you're on (docs vs feature); which could be more confusing than not having breadcrumbs.

---

![Screen Shot 2022-03-24 at 11 52 30 AM](https://user-images.githubusercontent.com/557895/159989715-dc6f22b8-0cc6-4c5d-a1c7-54e6a6e98e3c.png)
**Figure 1:** https://developer.mozilla.org/en-US/plus/docs/features/notifications (breadcrumb nav)

![Screen Shot 2022-03-24 at 11 52 41 AM](https://user-images.githubusercontent.com/557895/159989773-97e65153-64fa-4b83-bff8-d110526cb6e5.png)
**Figure 2:** https://developer.mozilla.org/en-US/plus/notifications (no breadcrumb nav)

**Comment by HerminaC** [comment]
Hey @pdehaan You are right, it is currently inconsistent but we are planning to do more work on breadcrumbs for overall MDN hence I would solve for all of this in one go, when we'll do that. Closing for now. Thanks!
